apiVersion: v1
kind: Pod
metadata:
  name: windows
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: windows
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["powershell.exe"]
    args:
      - "-command"
      - |
        $SleepTime = 8*60*60  # 8 hours in seconds
        Write-Output "Sleeping for $SleepTime seconds..."
        Start-Sleep -Seconds $SleepTime