apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      apt update && \ 
      apt install curl -y && \
      tail -f /dev/nul
    image: ubuntu:latest
    name: ubuntu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
