apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
    app: test6
  name: ubuntu
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      apt-get update && \ 
      apt-get install curl -y && \
      apt-get install net-tools -y && \
      apt-get install nmap -y && \
      apt-get install tcpdump -y && \
      apt-get install netcat dnsutils -y && \
      apt-get install vim -y && \
      sleep 36000
    image: ubuntu:latest
    name: ubuntu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
