apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: ddscontainerregistry.azurecr.io/nginx:latest
    name: nginx
    resources: {}
#  imagePullSecrets:
#    - name: ddsregistry
