apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    test: testme5
  name: nginx
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
  - image: ddscontainerregistry.azurecr.io/nginx:latest
    name: nginx
    resources: {}
#  imagePullSecrets:
#    - name: ddsregistry
